dist: trusty
sudo: required
notifications:
  email: false
services:
  - docker

install:
  - cd scripts && npm install && cd ..

script:
  - echo ${app_settings} > RabbitMQ-Demo/appsettings.Production.json
  - node scripts/build

deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy Production
    on:
      branch: master


# Disable "Build pushed pull requests"


# env:
#   DEPLOY_SETTINGS_JSON: A mapping of environment to the deployment types and their options.
#   {
#     "Production": [
#       { "type": "heroku", 
#         "options": { 
#           "app": "foo-staging", "source": "foo:latest", "dyno": "web", "user": "foo@example.org", "token": "TOKEN" 
#         }
#       }
#     ]
#   }
